export namespace SocketEvents {
  export const CLIENT_SENDS_IDENTIFICATION = 'CLIENT_SENDS_IDENTIFICATION';
  export const SERVER_PLAYER_NOT_FOUND = 'SERVER_PLAYER_NOT_FOUND';
  export const CLIENT_START_DRAFT = 'CLIENT_START_DRAFT';
  export const SERVER_UPDATE_JOINED_PLAYERS = 'SERVER_UPDATE_JOINED_PLAYERS';
  export const SERVER_BEGIN_DRAFT_COUNTDOWN = 'SERVER_BEGIN_DRAFT_COUNTDOWN';
  export const CLIENT_CANCEL_DRAFT_COUNTDOWN = 'CLIENT_CANCEL_DRAFT_COUNTDOWN';
  export const SERVER_DRAFT_COUNTDOWN_CANCELLED =
    'SERVER_DRAFT_COUNTDOWN_CANCELLED';
  export const CLIENT_CANCEL_DRAFT = 'CLIENT_CANCEL_DRAFT';
  export const SERVER_DRAFT_CANCELLED = 'SERVER_DRAFT_CANCELLED';
  export const CLIENT_REQUESTS_JOINED_PLAYERS =
    'CLIENT_REQUESTS_JOINED_PLAYERS';
  export const SERVER_DRAFT_TURNS_BEGIN = 'SERVER_DRAFT_TURNS_BEGIN';
  export const SERVER_SENDS_DRAFT_STATE = 'SERVER_SENDS_DRAFT_STATE';
  export const SERVER_DRAFT_ALREADY_STARTED = 'SERVER_DRAFT_ALREADY_STARTED';
  export const SERVER_STARTS_TURN = 'SERVER_STARTS_TURN';
  export const CLIENT_ENDS_TURN = 'CLIENT_ENDS_TURN';
  export const SERVER_UPDATE_TURN_TIMER = 'SERVER_UPDATE_TURN_TIMER';
  export const SERVER_DRAFT_CANCELLED_BY_OWNER =
    'SERVER_DRAFT_CANCELLED_BY_OWNER';
  export const SERVER_NO_PICK_RECEIVED = 'SERVER_NO_PICK_RECEIVED';
  export const CLIENT_SENDS_AUTO_PICK = 'CLIENT_SENDS_AUTO_PICK';
  export const SERVER_SENDS_PLAYER_PICK = 'SERVER_SENDS_PLAYER_PICK';
  export const CLIENT_LINEUP_COMPLETE = 'CLIENT_LINEUP_COMPLETE';
  export const SERVER_TOUR_NOT_FOUND = 'SERVER_TOUR_NOT_FOUND';
}
